CREATE TABLE PRODUCTS(
"ID" NUMBER NOT NULL PRIMARY KEY,
"CODE" NUMBER,
"CATEGORY" NVARCHAR2(255),
"EXPIRATION" NUMBER,
"PROVIDER" NVARCHAR2(255),
"UNITS" NVARCHAR2(255)
);
CREATE TABLE P_PRODUCTSIN(
"ID" NUMBER NOT NULL PRIMARY KEY,
"CODE" NUMBER NOT NULL,
"DATE" DATE NOT NULL,
"CONTRACT" NUMBER,
"AMOUNT_PROVIDED" NUMBER NOT NULL,
"AMOUNT_LEFT" NUMBER
);
