INSERT INTO P_PRODUCTS
("CODE", "NAME", "CATEGORY", "EXPIRATION", "PROVIDER", "UNITS")
VALUES
(111, 'NICE MILK', 'MILK', 5, 'MILK CO', 'UNIT');

INSERT INTO P_PRODUCTS
("CODE", "NAME", "CATEGORY", "EXPIRATION", "PROVIDER", "UNITS")
VALUES
(112, 'APPLES', 'FRUITS', 10, 'APPLE.INC CO', 'KG');

INSERT INTO P_PRODUCTS
("CODE", "NAME", "CATEGORY", "EXPIRATION", "PROVIDER", "UNITS")
VALUES
(113, 'RED POTATOES', 'VEGETABLES', 60, 'BELARUS CO', 'KG');

INSERT INTO P_PRODUCTS
("CODE", "NAME", "CATEGORY", "EXPIRATION", "PROVIDER", "UNITS")
VALUES
(114, 'ORANGES', 'FRUITS', 10, 'APPLE.INC CO', 'KG');

INSERT INTO P_PRODUCTS
("CODE", "NAME", "CATEGORY", "EXPIRATION", "PROVIDER", "UNITS")
VALUES
(115, 'BORDO WINE', 'ALCOHOL', 365, 'CRIMEA CO', 'UNIT');

INSERT INTO P_PRODUCTS
("CODE", "NAME", "CATEGORY", "EXPIRATION", "PROVIDER", "UNITS")
VALUES
(116, 'FINLANDIA', 'ALCOHOL', 365, 'FINKA CO', 'UNIT');

INSERT INTO P_PRODUCTS
("CODE", "NAME", "CATEGORY", "EXPIRATION", "PROVIDER", "UNITS")
VALUES
(117, 'CHEETOS', 'CHIPS', 60, 'HAVKA CO', 'UNIT');

INSERT INTO P_PRODUCTS
("CODE", "NAME", "CATEGORY", "EXPIRATION", "PROVIDER", "UNITS")
VALUES
(118, 'CHEESE', 'MILK', 40, 'SWITZ CHEESE', 'KG');

INSERT INTO P_PRODUCTS
("CODE", "NAME", "CATEGORY", "EXPIRATION", "PROVIDER", "UNITS")
VALUES
(119, 'CARROTS', 'VEGETABLES', 20, 'VEGIES CO', 'KG');

INSERT INTO P_PRODUCTS
("CODE", "NAME", "CATEGORY", "EXPIRATION", "PROVIDER", "UNITS")
VALUES
(120, 'ABSOLUT', 'ALCOHOL', 365, 'RUSSIAN VODKA', 'UNIT');

INSERT INTO P_PRODUCTS
("CODE", "NAME", "CATEGORY", "EXPIRATION", "PROVIDER", "UNITS")
VALUES
(121, 'APPLE JUICE', 'JUICES', 60, 'APPLE.INC CO', 'UNIT');



INSERT INTO P_PRODUCTSIN 
("CODE", "DATE", "CONTRACT", "AMOUNT_PROVIDED")
VALUES
(111, '12/MAY/2017', 911, 10);

INSERT INTO P_PRODUCTSIN 
("CODE", "DATE", "CONTRACT", "AMOUNT_PROVIDED")
VALUES
(113, '13/APRIL/2017', 912, 15);

INSERT INTO P_PRODUCTSIN 
("CODE", "DATE", "CONTRACT", "AMOUNT_PROVIDED")
VALUES
(116, '25/FEBRUARY/2017', 914, 17);

INSERT INTO P_PRODUCTSIN 
("CODE", "DATE", "CONTRACT", "AMOUNT_PROVIDED")
VALUES
(121, '25/MAY/2017', 1011, 50);

INSERT INTO P_PRODUCTSIN
("CODE", "DATE", "CONTRACT", "AMOUNT_PROVIDED")
VALUES
(119, '20/MAY/2017', 1023, 60);
